"""Archivist Agent: produces living artifacts from graph + semantic analysis results.

Artifacts:
  - CODEBASE.md          Living context file for AI coding agent injection
  - onboarding_brief.md  Five FDE Day-One answers with evidence
  - cartography_trace.jsonl  Audit log of every analysis action
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.graph import LineageGraph, ModuleGraph
from src.llm_config import LLMConfig, build_cloud_config, chat_completion, load_config


# ---------------------------------------------------------------------------
# Trace logger
# ---------------------------------------------------------------------------

class TraceLogger:
    """Append-only JSONL audit log of agent actions."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.path.parent.mkdir(parents=True, exist_ok=True)

    def log(
        self,
        agent: str,
        action: str,
        details: dict[str, Any] | None = None,
        confidence: str = "high",
        source: str = "static_analysis",
    ) -> None:
        """Append one trace entry.

        Args:
            agent: Name of the agent emitting this entry.
            action: Short description of the action taken.
            details: Optional structured details (file paths, counts, etc.).
            confidence: "high" | "medium" | "low"
            source: "static_analysis" | "llm_inference" | "git_analysis"
        """
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent": agent,
            "action": action,
            "confidence": confidence,
            "evidence_source": source,
            "details": details or {},
        }
        with self.path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")


# ---------------------------------------------------------------------------
# CODEBASE.md generation
# ---------------------------------------------------------------------------

def _top_modules_by_pagerank(module_graph: ModuleGraph, n: int = 5) -> list[dict[str, Any]]:
    G = module_graph.graph
    ranked = sorted(
        (
            (node, G.nodes[node])
            for node in G.nodes()
            if G.nodes[node].get("node_type") == "module"
        ),
        key=lambda x: x[1].get("pagerank", 0.0),
        reverse=True,
    )
    return [{"path": p, **attrs} for p, attrs in ranked[:n]]


def _high_velocity_files(module_graph: ModuleGraph, n: int = 10) -> list[dict[str, Any]]:
    G = module_graph.graph
    ranked = sorted(
        (
            (node, G.nodes[node])
            for node in G.nodes()
            if G.nodes[node].get("node_type") == "module"
        ),
        key=lambda x: x[1].get("change_velocity_30d", 0),
        reverse=True,
    )
    return [
        {"path": p, "commits": attrs.get("change_velocity_30d", 0)}
        for p, attrs in ranked[:n]
        if attrs.get("change_velocity_30d", 0) > 0
    ]


def _circular_deps(module_graph: ModuleGraph) -> list[list[str]]:
    import networkx as nx
    G = module_graph.graph
    return [list(c) for c in nx.strongly_connected_components(G) if len(c) > 1]


def _domain_summary(module_graph: ModuleGraph) -> dict[str, list[str]]:
    G = module_graph.graph
    domains: dict[str, list[str]] = {}
    for node in G.nodes():
        if G.nodes[node].get("node_type") != "module":
            continue
        domain = G.nodes[node].get("domain_cluster") or "unknown"
        domains.setdefault(domain, []).append(node)
    return domains


def _doc_drift_modules(module_graph: ModuleGraph) -> list[dict[str, str]]:
    G = module_graph.graph
    drifts = []
    for node in G.nodes():
        if G.nodes[node].get("doc_drift"):
            drifts.append({"path": node, "summary": G.nodes[node]["doc_drift"]})
    return drifts


def generate_codebase_md(
    module_graph: ModuleGraph,
    lineage_graph: LineageGraph,
    semantic_results: dict[str, Any] | None = None,
    *,
    config: LLMConfig | None = None,
    config_path: str | Path | None = None,
) -> str:
    """Generate the CODEBASE.md living context file content.

    The architecture overview paragraph is generated by the LLM.
    All other sections are derived from graph data (static analysis).
    """
    if config is None:
        config = load_config(config_path)

    G_mod = module_graph.graph
    G_lin = lineage_graph.graph

    top_modules = _top_modules_by_pagerank(module_graph, n=5)
    hot_files = _high_velocity_files(module_graph, n=10)
    circular = _circular_deps(module_graph)
    domains = _domain_summary(module_graph)
    drift_modules = _doc_drift_modules(module_graph)
    sources = lineage_graph.find_sources()[:10]
    sinks = lineage_graph.find_sinks()[:10]

    # LLM-generated architecture overview
    module_list = "\n".join(
        f"- {m['path']} (pagerank={m.get('pagerank', 0):.4f}, "
        f"lang={m.get('language', '?')}, "
        f"purpose={m.get('purpose_statement', 'unknown')[:120]})"
        for m in top_modules
    )
    messages = [
        {
            "role": "system",
            "content": (
                "You write concise architectural overviews for software engineers. "
                "Given a list of the most important modules in a codebase, write a single "
                "paragraph (3-5 sentences) describing the system's architecture. "
                "Be specific about what the system does, its key components, and data flow direction."
            ),
        },
        {
            "role": "user",
            "content": (
                f"Top modules by architectural importance (PageRank):\n{module_list}\n\n"
                f"Total modules: {G_mod.number_of_nodes()}\n"
                f"Total lineage nodes: {G_lin.number_of_nodes()}\n"
                f"Data sources: {', '.join(sources[:5]) or 'none detected'}\n"
                f"Data sinks: {', '.join(sinks[:5]) or 'none detected'}\n\n"
                "Write the architecture overview paragraph."
            ),
        },
    ]
    try:
        arch_overview = chat_completion(messages, config=config, max_tokens=256).strip()
    except Exception as exc:
        arch_overview = f"[LLM error generating overview: {exc}]"

    # Build the markdown sections
    lines: list[str] = [
        "# CODEBASE.md — Living Context File",
        f"\n_Generated by Brownfield Cartographer on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_\n",
        "---\n",
        "## Architecture Overview\n",
        arch_overview,
        "\n---\n",
        "## Critical Path (Top 5 Modules by PageRank)\n",
    ]
    for m in top_modules:
        purpose = m.get("purpose_statement") or "_(no purpose statement)_"
        lines.append(
            f"- **`{m['path']}`** (pagerank={m.get('pagerank', 0):.4f})  \n"
            f"  {purpose}\n"
        )

    lines += ["\n---\n", "## Data Sources & Sinks\n", "**Sources (entry points):**\n"]
    for s in sources:
        lines.append(f"- `{s}`\n")
    if not sources:
        lines.append("- _(none detected)_\n")

    lines.append("\n**Sinks (output endpoints):**\n")
    for s in sinks:
        lines.append(f"- `{s}`\n")
    if not sinks:
        lines.append("- _(none detected)_\n")

    lines += ["\n---\n", "## Domain Architecture Map\n"]
    for domain, mods in sorted(domains.items()):
        lines.append(f"**{domain.capitalize()}** ({len(mods)} modules):\n")
        for mod in sorted(mods)[:8]:
            lines.append(f"- `{mod}`\n")
        if len(mods) > 8:
            lines.append(f"- _…and {len(mods) - 8} more_\n")
        lines.append("\n")

    lines += ["\n---\n", "## Known Debt\n"]
    if circular:
        lines.append("**Circular dependencies:**\n")
        for cycle in circular[:5]:
            lines.append(f"- {' → '.join(cycle[:6])}{'…' if len(cycle) > 6 else ''}\n")
    else:
        lines.append("- No circular dependencies detected.\n")

    if drift_modules:
        lines.append("\n**Documentation drift (docstring contradicts implementation):**\n")
        for d in drift_modules[:10]:
            lines.append(f"- `{d['path']}`: {d['summary']}\n")
    else:
        lines.append("\n- No documentation drift detected.\n")

    lines += ["\n---\n", "## High-Velocity Files (Pain Points)\n"]
    if hot_files:
        for f in hot_files:
            lines.append(f"- `{f['path']}` — {f['commits']} commits (last 30d)\n")
    else:
        lines.append("- _(git velocity data unavailable — not a git repo or no recent commits)_\n")

    lines += ["\n---\n", "## Module Purpose Index\n"]
    for node in sorted(G_mod.nodes()):
        if G_mod.nodes[node].get("node_type") != "module":
            continue
        purpose = G_mod.nodes[node].get("purpose_statement")
        if purpose:
            lines.append(f"- **`{node}`**: {purpose}\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Onboarding brief
# ---------------------------------------------------------------------------

def generate_onboarding_brief(
    day_one_answers: dict[str, str],
    module_graph: ModuleGraph,
    lineage_graph: LineageGraph,
) -> str:
    """Generate onboarding_brief.md from Day-One answers and graph data."""
    top = _top_modules_by_pagerank(module_graph, n=5)
    sources = lineage_graph.find_sources()[:5]
    sinks = lineage_graph.find_sinks()[:5]
    G = module_graph.graph

    lines = [
        "# FDE Day-One Onboarding Brief\n",
        f"\n_Generated by Brownfield Cartographer — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_\n",
        "\n---\n",
        "## The Five FDE Day-One Questions\n",
    ]

    for i, (question, answer) in enumerate(day_one_answers.items(), start=1):
        lines.append(f"\n### Q{i}: {question}\n\n{answer}\n")

    lines += [
        "\n---\n",
        "## Quick-Reference Architecture\n",
        "\n**Top modules (by architectural centrality):**\n",
    ]
    for m in top:
        attrs = G.nodes.get(m["path"], {})
        meta_parts = [f"pagerank={m.get('pagerank', 0):.4f}"]
        if attrs.get("line_count"):
            meta_parts.append(f"lines 1–{attrs['line_count']}")
        if attrs.get("complexity_score") is not None:
            meta_parts.append(f"complexity={attrs['complexity_score']:.1f}")
        if attrs.get("change_velocity_30d"):
            meta_parts.append(f"{attrs['change_velocity_30d']} commits/30d")
        lines.append(f"- `{m['path']}` ({', '.join(meta_parts)})\n")
        if attrs.get("purpose_statement"):
            lines.append(f"  _{attrs['purpose_statement'][:120]}_\n")

    lines.append("\n**Data entry points:**\n")
    for s in sources:
        attrs = G.nodes.get(s, {})
        loc = f" — `{attrs.get('source_file', s)}`" if attrs.get("source_file") else ""
        lines.append(f"- `{s}`{loc}\n")
    if not sources:
        lines.append("- _(none detected)_\n")

    lines.append("\n**Data output endpoints:**\n")
    for s in sinks:
        attrs = G.nodes.get(s, {})
        loc = f" — `{attrs.get('source_file', s)}`" if attrs.get("source_file") else ""
        lines.append(f"- `{s}`{loc}\n")
    if not sinks:
        lines.append("- _(none detected)_\n")

    # Evidence citations: top modules with available line-range metadata
    lines += ["\n---\n", "## Evidence: Module Citation Index\n"]
    evidence_modules = _top_modules_by_pagerank(module_graph, n=10)
    for m in evidence_modules:
        path = m["path"]
        attrs = G.nodes.get(path, {})
        evidence_parts: list[str] = []
        if attrs.get("line_count"):
            evidence_parts.append(f"lines 1–{attrs['line_count']}")
        if attrs.get("complexity_score") is not None:
            evidence_parts.append(f"complexity={attrs['complexity_score']:.1f}")
        if attrs.get("change_velocity_30d"):
            evidence_parts.append(f"{attrs['change_velocity_30d']} commits/30d")
        if attrs.get("domain_cluster"):
            evidence_parts.append(f"domain={attrs['domain_cluster']}")
        evidence_str = ", ".join(evidence_parts) if evidence_parts else "no metadata"
        lines.append(f"- `{path}` ({evidence_str})\n")

    return "".join(lines)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def archive(
    module_graph: ModuleGraph,
    lineage_graph: LineageGraph,
    semantic_results: dict[str, Any] | None = None,
    *,
    output_dir: str | Path = ".cartography",
    config: LLMConfig | None = None,
    config_path: str | Path | None = None,
    trace_logger: TraceLogger | None = None,
) -> dict[str, str]:
    """Run the Archivist: write CODEBASE.md, onboarding_brief.md, cartography_trace.jsonl.

    Returns:
        Dict with keys: codebase_md_path, onboarding_brief_path, trace_path
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if config is None:
        config = load_config(config_path)

    # Escalate to cloud model for large repos (same threshold as Semanticist)
    python_modules = [
        n for n in module_graph.graph.nodes()
        if module_graph.graph.nodes[n].get("node_type") == "module"
        and module_graph.graph.nodes[n].get("language") == "python"
    ]
    if len(python_modules) > config.large_repo_threshold and config.cloud_model:
        print(
            f"[Archivist] Large repo ({len(python_modules)} Python modules > {config.large_repo_threshold})"
            f" — escalating to {config.cloud_model} ...",
            flush=True,
        )
        config = build_cloud_config(config)

    trace_path = output_dir / "cartography_trace.jsonl"
    if trace_logger is None:
        trace_logger = TraceLogger(trace_path)

    print("[Archivist] Generating CODEBASE.md ...", flush=True)
    trace_logger.log(
        "Archivist", "generate_codebase_md",
        details={"output": str(output_dir / "CODEBASE.md")},
        source="llm_inference",
    )
    codebase_md = generate_codebase_md(
        module_graph, lineage_graph,
        semantic_results=semantic_results,
        config=config,
    )
    codebase_md_path = output_dir / "CODEBASE.md"
    codebase_md_path.write_text(codebase_md, encoding="utf-8")

    print("[Archivist] Generating onboarding_brief.md ...", flush=True)
    day_one_answers = (semantic_results or {}).get("day_one_answers", {})
    if not day_one_answers:
        day_one_answers = {"(no semantic analysis run)": "Run with --llm to generate Day-One answers."}

    trace_logger.log(
        "Archivist", "generate_onboarding_brief",
        details={"output": str(output_dir / "onboarding_brief.md"), "answers_count": len(day_one_answers)},
        source="llm_inference",
    )
    brief_md = generate_onboarding_brief(day_one_answers, module_graph, lineage_graph)
    brief_path = output_dir / "onboarding_brief.md"
    brief_path.write_text(brief_md, encoding="utf-8")

    trace_logger.log(
        "Archivist", "archive_complete",
        details={
            "codebase_md": str(codebase_md_path),
            "onboarding_brief": str(brief_path),
            "trace": str(trace_path),
        },
        confidence="high",
        source="static_analysis",
    )

    G = module_graph.graph
    G_lin = lineage_graph.graph
    print(
        f"[Archivist] Done: CODEBASE.md ({len(codebase_md)} chars), "
        f"onboarding_brief.md, trace log → {output_dir}",
        flush=True,
    )

    return {
        "codebase_md_path": str(codebase_md_path),
        "onboarding_brief_path": str(brief_path),
        "trace_path": str(trace_path),
    }
